### ISSUE TITLE
The mbed-os.lib should have commit hash

### ISSUE THREAD

**Issue by toyowata** [ARMmbed/mbed-os-example-cellular#113]
Current mbed-os.lib file points to the correct GitHub repo, but no commit hash. 

https://github.com/ARMmbed/mbed-os-example-cellular/blob/master/mbed-os.lib

This means we could have non-single version of the example code because mbed import (or mbed deploy) copies from newest mater branch, even not latest release.

**Comment by adbridge** [comment]
@toyowata I believe this will be fixed when we release mbed-os-5.11

**Comment by 0xc0170** [comment]
https://github.com/ARMmbed/mbed-os-example-cellular/blob/mbed-os-5.11.0-oob/mbed-os.lib 👍
