### ISSUE TITLE
In readme, link to cellular documentation doesn't work

### ISSUE THREAD

**Issue by szymsta** [ARMmbed/mbed-os-example-cellular#120]
In readme, there is a reference to Mbed OS cellular documentation (https://os.mbed.com/docs/mbed-os/v5.11/reference/cellular-api.html), that page doesn't exist, though.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCELL-1705

**Comment by mirelachirica** [comment]
Fixed in commit: https://github.com/ARMmbed/mbed-os-example-cellular/commit/d79c6fd959a7364a797a84c733afb24151c576a6
