### ISSUE TITLE
Need example updated to Mbed OS 5.12+

### ISSUE THREAD

**Issue by MarceloSalazar** [ARMmbed/mbed-os-example-cellular#132]
Please update mbed-os.lib and required configuration (mbed_app.json) for multiple platforms/shields to use this example as a reference for Mbed OS 5.12 based applications.
Thanks!

**Comment by MarceloSalazar** [comment]
Related to https://github.com/ARMmbed/mbed-os-example-cellular/pull/131

**Comment by AnttiKauppila** [comment]
@MarceloSalazar Which platforms are you referring?

**Comment by MarceloSalazar** [comment]
From my point of view, is not a problem about platform, but rather configuration to enable a shield using serial/SPI (as I understand there is a new way of doing this in 5.12).
Can be K64 or L475 platforms with both BG96 or Gemalto shields.

Once this new config is in place, we can introduce more for other shields that are currently in the works.

**Comment by AnttiKauppila** [comment]
@AriParkkila Can you help with this?

**Comment by AriParkkila** [comment]
@MarceloSalazar It's now updated to Mbed OS 5.12+. Can we close this ticket?

**Comment by MarceloSalazar** [comment]
Yes, thank you!
