### ISSUE TITLE
Inconsistent field names in troubleshooting section

### ISSUE THREAD

**Issue by hugueskamba** [ARMmbed/mbed-os-example-cellular#146]
The section reads:

> Make sure the fields sim-pin-code, apn, username and password from the mbed_app.json file are filled in correctly. The correct values should appear in the user manual of the board if using eSIM or in the details of the SIM card if using normal SIM.

It should really say:

> Make sure the fields `nsapi.default-cellular-sim-pin`, `nsapi.default-cellular-apn`, `nsapi.default-cellular-username` and `nsapi.default-cellular-password` from the mbed_app.json file are filled in correctly. The correct values should appear in the user manual of the board if using eSIM or in the details of the SIM card if using normal SIM.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCELL-2092

**Comment by AriParkkila** [comment]
Fix in PR #160.
