### ISSUE TITLE
CY8CKIT-062-BLE not detected by 'mbed detect'

### ISSUE THREAD

**Issue by vladdnikolic** [ARMmbed/mbed-os-example-cellular#154]
I have a Cypress CY8CKIT-062-BLE kit. When I run the command `mbed detect` I get this message

`[mbed] Detected None, port COM31, mounted D:, interface version 0254:
[mbed] Supported toolchains for None
| Target               | mbed OS 2 | mbed OS 5 |    uARM   |    IAR    |    ARM    |  GCC_ARM  | ARMC5 |
|----------------------|-----------|-----------|-----------|-----------|-----------|-----------|-------|
| ARCH_MAX             | Supported | Supported | Supported | Supported | Supported | Supported |   -   |
| ARCH_PRO             | Supported | Supported | Supported | Supported | Supported | Supported |   -   |
| ARM_CM3DS_MPS2       | Supported | Supported |     -     | Supported | Supported | Supported |   -   |
| ARM_MPS2_M0          | Supported | Supported |     -     | Supported | Supported | Supported |   -   |
| ARM_MPS2_M0P         | Supported | Supported |     -     | Supported | Supported | Supported |   -   |
| ARM_MPS2_M3          | Supported | Supported |     -     | Supported | Supported | Supported |   -   |
| ARM_MPS2_M4          | Supported | Supported |     -     | Supported | Supported | Supported |   -   |
| ARM_MPS2_M7          | Supported | Supported |     -     | Supported | Supported | Supported |   -   |
| ARM_MUSCA_A1_NS      |     -     | Supported |     -     | Supported | Supported | Supported |   -   |
| B96B_F446VE          | Supported | Supported | Supported | Supported | Supported | Supported |   -   |
| CY8CKIT_062_BLE      |     -     | Supported |     -     | Supported | Supported | Supported |   -   |
| CY8CKIT_062_WIFI_BT  |     -     | Supported |     -     | Supported | Supported | Supported |   -   |
| CY8CPROTO_062_4343W  |     -     | Supported |     -     | Supported | Supported | Supported |   -   |
| CYW943012P6EVB_01    |     -     | Supported |     -     | Supported | Supported | Supported |   -   |
| DELTA_DFBM_NQ620     |     -     | Supported |     -     | Supported | Supported | Supported |   -   |
| DISCO_F303VC         | Supported | Supported | Supported | Supported | Supported | Supported |   -   |
| DISCO_F407VG         | Supported | Supported | Supported | Supported | Supported | Supported |   -   |
| DISCO_F413ZH         | Supported | Supported | Supported | Supported | Supported | Supported |   -   |
| DISCO_F429ZI         | Supported | Supported | Supported | Supported | Supported | Supported |   -   |
| DISCO_F469NI         | Supported | Supported | Supported | Supported | Supported | Supported |   -   |
| DISCO_F746NG         | Supported | Supported | Supported | Supported | Supported | Supported |   -   |
| DISCO_F769NI         | Supported | Supported | Supported | Supported | Supported | Supported |   -   |
| DISCO_L072CZ_LRWAN1  | Supported | Supported | Supported | Supported | Supported | Supported |   -   |
| DISCO_L475VG_IOT01A  | Supported | Supported | Supported | Supported | Supported | Supported |   -   |
| DISCO_L476VG         | Supported | Supported | Supported | Supported | Supported | Supported |   -   |
| DISCO_L496AG         | Supported | Supported | Supported | Supported | Supported | Supported |   -   |
| EFM32GG11_STK3701    | Supported | Supported | Supported | Supported | Supported | Supported |   -   |
| EFM32GG_STK3700      | Supported | Supported | Supported | Supported | Supported | Supported |   -   |
| EFM32LG_STK3600      | Supported | Supported | Supported | Supported | Supported | Supported |   -   |
| EFM32PG12_STK3402    | Supported | Supported | Supported | Supported | Supported | Supported |   -   |
| EFM32PG_STK3401      | Supported | Supported | Supported | Supported | Supported | Supported |   -   |
| EFM32WG_STK3800      | Supported | Supported | Supported | Supported | Supported | Supported |   -   |
| EP_AGORA             |     -     | Supported |     -     | Supported | Supported | Supported |   -   |
| EV_COG_AD3029LZ      |     -     | Supported |     -     | Supported | Supported | Supported |   -   |
| EV_COG_AD4050LZ      |     -     | Supported |     -     | Supported | Supported | Supported |   -   |
| FF1705_L151CC        |     -     | Supported |     -     | Supported | Supported | Supported |   -   |
| FF_LPC546XX          | Supported | Supported |     -     | Supported | Supported | Supported |   -   |
| FUTURE_SEQUANA       |     -     | Supported |     -     | Supported | Supported | Supported |   -   |
| FUTURE_SEQUANA_M0    |     -     | Supported |     -     | Supported | Supported | Supported |   -   |
| FVP_MPS2_M0          |     -     | Supported |     -     | Supported | Supported | Supported |   -   |
| FVP_MPS2_M0P         |     -     | Supported |     -     | Supported | Supported | Supported |   -   |
| FVP_MPS2_M3          |     -     | Supported |     -     | Supported | Supported | Supported |   -   |
| FVP_MPS2_M4          |     -     | Supported |     -     | Supported | Supported | Supported |   -   |
| FVP_MPS2_M7          |     -     | Supported |     -     | Supported | Supported | Supported |   -   |
| GD32_E103VB          |     -     | Supported |     -     | Supported | Supported | Supported |   -   |
| GD32_F307VG          |     -     | Supported |     -     | Supported | Supported | Supported |   -   |
| GD32_F450ZI          |     -     | Supported |     -     | Supported | Supported | Supported |   -   |
| GR_LYCHEE            | Supported | Supported |     -     | Supported | Supported | Supported |   -   |
| HEXIWEAR             | Supported | Supported |     -     | Supported | Supported | Supported |   -   |
| IM880B               |     -     | Supported |     -     | Supported | Supported | Supported |   -   |
| K22F                 | Supported | Supported |     -     | Supported | Supported | Supported |   -   |
| K64F                 | Supported | Supported |     -     | Supported | Supported | Supported |   -   |
| K66F                 | Supported | Supported |     -     | Supported | Supported | Supported |   -   |
| K82F                 | Supported | Supported |     -     | Supported | Supported | Supported |   -   |
| KL25Z                | Supported | Supported |     -     | Supported | Supported | Supported |   -   |
| KL43Z                | Supported | Supported |     -     | Supported | Supported | Supported |   -   |
| KL46Z                | Supported | Supported |     -     | Supported | Supported | Supported |   -   |
| KL82Z                | Supported | Supported |     -     | Supported | Supported | Supported |   -   |
| KW24D                | Supported | Supported |     -     | Supported | Supported | Supported |   -   |
| KW41Z                | Supported | Supported |     -     | Supported | Supported | Supported |   -   |
| LPC1768              | Supported | Supported | Supported | Supported | Supported | Supported |   -   |
| LPC1769              | Supported | Supported | Supported | Supported | Supported | Supported |   -   |
| LPC4088              | Supported | Supported |     -     | Supported | Supported | Supported |   -   |
| LPC4088_DM           | Supported | Supported |     -     | Supported | Supported | Supported |   -   |
| LPC54114             | Supported | Supported |     -     | Supported | Supported | Supported |   -   |
| LPC546XX             | Supported | Supported |     -     | Supported | Supported | Supported |   -   |
| LPC55S69_NS          |     -     | Supported |     -     | Supported | Supported | Supported |   -   |
| MAX32600MBED         | Supported | Supported |     -     | Supported | Supported | Supported |   -   |
| MAX32620FTHR         | Supported | Supported |     -     | Supported | Supported | Supported |   -   |
| MAX32625MBED         | Supported | Supported |     -     | Supported | Supported | Supported |   -   |
| MAX32625NEXPAQ       | Supported | Supported |     -     | Supported | Supported | Supported |   -   |
| MAX32625PICO         | Supported | Supported |     -     | Supported | Supported | Supported |   -   |
| MAX32630FTHR         | Supported | Supported |     -     | Supported | Supported | Supported |   -   |
| MBED_CONNECT_ODIN    |     -     | Supported | Supported | Supported | Supported | Supported |   -   |
| MIMXRT1050_EVK       | Supported | Supported |     -     | Supported | Supported | Supported |   -   |
| MOTE_L152RC          | Supported | Supported |     -     | Supported | Supported | Supported |   -   |
| MTB_ACONNO_ACN52832  |     -     | Supported |     -     | Supported | Supported | Supported |   -   |
| MTB_ADV_WISE_1510    |     -     | Supported | Supported | Supported | Supported | Supported |   -   |
| MTB_ADV_WISE_1530    |     -     | Supported |     -     | Supported | Supported | Supported |   -   |
| MTB_ADV_WISE_1570    |     -     | Supported | Supported | Supported | Supported | Supported |   -   |
| MTB_LAIRD_BL600      |     -     | Supported |     -     | Supported | Supported | Supported |   -   |
| MTB_LAIRD_BL652      |     -     | Supported |     -     | Supported | Supported | Supported |   -   |
| MTB_LAIRD_BL654      |     -     | Supported |     -     | Supported | Supported | Supported |   -   |
| MTB_MTS_DRAGONFLY    | Supported | Supported | Supported | Supported | Supported | Supported |   -   |
| MTB_MTS_XDOT         |     -     | Supported |     -     | Supported | Supported | Supported |   -   |
| MTB_MURATA_ABZ       |     -     | Supported | Supported | Supported | Supported | Supported |   -   |
| MTB_MURATA_WSM_BL241 |     -     | Supported |     -     | Supported | Supported | Supported |   -   |
| MTB_MXCHIP_EMW3166   |     -     | Supported |     -     | Supported | Supported | Supported |   -   |
| MTB_RAK811           |     -     | Supported |     -     | Supported | Supported | Supported |   -   |
| MTB_STM32_F439       |     -     | Supported | Supported | Supported | Supported | Supported |   -   |
| MTB_STM_L475         |     -     | Supported | Supported | Supported | Supported | Supported |   -   |
| MTB_STM_S2LP         |     -     | Supported | Supported | Supported | Supported | Supported |   -   |
| MTB_UBLOX_NINA_B1    |     -     | Supported |     -     | Supported | Supported | Supported |   -   |
| MTB_UBLOX_ODIN_W2    |     -     | Supported | Supported | Supported | Supported | Supported |   -   |
| MTB_USI_WM_BN_BM_22  |     -     | Supported |     -     | Supported | Supported | Supported |   -   |
| MTS_DRAGONFLY_F411RE | Supported | Supported | Supported | Supported | Supported | Supported |   -   |
| MTS_DRAGONFLY_L471QG | Supported | Supported | Supported | Supported | Supported | Supported |   -   |
| MTS_MDOT_F411RE      | Supported | Supported | Supported | Supported | Supported | Supported |   -   |
| NCS36510             | Supported | Supported |     -     | Supported | Supported | Supported |   -   |
| NRF51_DK             | Supported | Supported |     -     | Supported | Supported | Supported |   -   |
| NRF51_DONGLE         | Supported | Supported |     -     | Supported | Supported | Supported |   -   |
| NRF52840_DK          |     -     | Supported |     -     | Supported | Supported | Supported |   -   |
| NRF52_DK             |     -     | Supported |     -     | Supported | Supported | Supported |   -   |
| NUCLEO_F070RB        | Supported | Supported | Supported | Supported | Supported | Supported |   -   |
| NUCLEO_F072RB        | Supported | Supported | Supported | Supported | Supported | Supported |   -   |
| NUCLEO_F091RC        | Supported | Supported | Supported | Supported | Supported | Supported |   -   |
| NUCLEO_F103RB        | Supported | Supported | Supported | Supported | Supported | Supported |   -   |
| NUCLEO_F207ZG        | Supported | Supported | Supported | Supported | Supported | Supported |   -   |
| NUCLEO_F303RE        | Supported | Supported | Supported | Supported | Supported | Supported |   -   |
| NUCLEO_F303ZE        | Supported | Supported | Supported | Supported | Supported | Supported |   -   |
| NUCLEO_F401RE        | Supported | Supported | Supported | Supported | Supported | Supported |   -   |
| NUCLEO_F410RB        | Supported | Supported | Supported | Supported | Supported | Supported |   -   |
| NUCLEO_F411RE        | Supported | Supported | Supported | Supported | Supported | Supported |   -   |
| NUCLEO_F412ZG        | Supported | Supported | Supported | Supported | Supported | Supported |   -   |
| NUCLEO_F413ZH        | Supported | Supported | Supported | Supported | Supported | Supported |   -   |
| NUCLEO_F429ZI        | Supported | Supported | Supported | Supported | Supported | Supported |   -   |
| NUCLEO_F439ZI        | Supported | Supported | Supported | Supported | Supported | Supported |   -   |
| NUCLEO_F446RE        | Supported | Supported | Supported | Supported | Supported | Supported |   -   |
| NUCLEO_F446ZE        | Supported | Supported | Supported | Supported | Supported | Supported |   -   |
| NUCLEO_F746ZG        | Supported | Supported | Supported | Supported | Supported | Supported |   -   |
| NUCLEO_F756ZG        | Supported | Supported | Supported | Supported | Supported | Supported |   -   |
| NUCLEO_F767ZI        | Supported | Supported | Supported | Supported | Supported | Supported |   -   |
| NUCLEO_H743ZI        | Supported | Supported | Supported | Supported | Supported | Supported |   -   |
| NUCLEO_H743ZI2       | Supported | Supported | Supported | Supported | Supported | Supported |   -   |
| NUCLEO_L073RZ        | Supported | Supported | Supported | Supported | Supported | Supported |   -   |
| NUCLEO_L152RE        | Supported | Supported | Supported | Supported | Supported | Supported |   -   |
| NUCLEO_L432KC        | Supported | Supported | Supported | Supported | Supported | Supported |   -   |
| NUCLEO_L433RC_P      | Supported | Supported | Supported | Supported | Supported | Supported |   -   |
| NUCLEO_L476RG        | Supported | Supported | Supported | Supported | Supported | Supported |   -   |
| NUCLEO_L486RG        | Supported | Supported | Supported | Supported | Supported | Supported |   -   |
| NUCLEO_L496ZG        | Supported | Supported | Supported | Supported | Supported | Supported |   -   |
| NUCLEO_L496ZG_P      | Supported | Supported | Supported | Supported | Supported | Supported |   -   |
| NUCLEO_L4R5ZI        | Supported | Supported | Supported | Supported | Supported | Supported |   -   |
| NUCLEO_L4R5ZI_P      | Supported | Supported | Supported | Supported | Supported | Supported |   -   |
| NUCLEO_WB55RG        | Supported | Supported | Supported | Supported | Supported | Supported |   -   |
| NUMAKER_IOT_M487     |     -     | Supported | Supported | Supported | Supported | Supported |   -   |
| NUMAKER_PFM_M2351    |     -     | Supported |     -     |     -     | Supported |     -     |   -   |
| NUMAKER_PFM_M453     | Supported | Supported | Supported | Supported | Supported | Supported |   -   |
| NUMAKER_PFM_M487     |     -     | Supported | Supported | Supported | Supported | Supported |   -   |
| NUMAKER_PFM_NANO130  |     -     | Supported | Supported | Supported | Supported | Supported |   -   |
| NUMAKER_PFM_NUC472   |     -     | Supported | Supported | Supported | Supported | Supported |   -   |
| RAPIDIOT_K64F        | Supported | Supported |     -     | Supported | Supported | Supported |   -   |
| RAPIDIOT_KW41Z       | Supported | Supported |     -     | Supported | Supported | Supported |   -   |
| RBLAB_BLENANO2       |     -     | Supported |     -     | Supported | Supported | Supported |   -   |
| RDA5981X             | Supported | Supported |     -     | Supported | Supported | Supported |   -   |
| RHOMBIO_L476DMW1K    | Supported | Supported | Supported | Supported | Supported | Supported |   -   |
| RO359B               | Supported | Supported |     -     | Supported | Supported | Supported |   -   |
| RZ_A1H               | Supported | Supported |     -     | Supported | Supported | Supported |   -   |
| SDP_K1               |     -     | Supported | Supported | Supported | Supported | Supported |   -   |
| SDT32620B            | Supported | Supported |     -     | Supported | Supported | Supported |   -   |
| SDT32625B            | Supported | Supported |     -     | Supported | Supported | Supported |   -   |
| SDT51822B            | Supported | Supported |     -     | Supported | Supported | Supported |   -   |
| SDT52832B            |     -     | Supported |     -     | Supported | Supported | Supported |   -   |
| SDT64B               | Supported | Supported |     -     | Supported | Supported | Supported |   -   |
| SILICA_SENSOR_NODE   |     -     | Supported | Supported | Supported | Supported | Supported |   -   |
| STEVAL_3DP001V1      | Supported | Supported | Supported | Supported | Supported | Supported |   -   |
| TB_SENSE_1           | Supported | Supported | Supported | Supported | Supported | Supported |   -   |
| TB_SENSE_12          | Supported | Supported | Supported | Supported | Supported | Supported |   -   |
| TMPM066              |     -     | Supported |     -     | Supported | Supported | Supported |   -   |
| TMPM3H6              |     -     | Supported |     -     | Supported | Supported | Supported |   -   |
| TMPM3HQ              |     -     | Supported |     -     | Supported | Supported | Supported |   -   |
| TMPM46B              |     -     | Supported |     -     | Supported | Supported | Supported |   -   |
| TMPM4G9              |     -     | Supported |     -     | Supported | Supported | Supported |   -   |
| TT_M3HQ              |     -     | Supported |     -     | Supported | Supported | Supported |   -   |
| TT_M4G9              |     -     | Supported |     -     | Supported | Supported | Supported |   -   |
| TY51822R3            | Supported | Supported |     -     | Supported | Supported | Supported |   -   |
| UBLOX_C027           | Supported | Supported | Supported | Supported | Supported | Supported |   -   |
| UBLOX_C030_N211      |     -     | Supported |     -     | Supported | Supported | Supported |   -   |
| UBLOX_C030_R410M     |     -     | Supported |     -     | Supported | Supported | Supported |   -   |
| UBLOX_C030_R412M     |     -     | Supported |     -     | Supported | Supported | Supported |   -   |
| UBLOX_C030_R41XM     |     -     | Supported |     -     | Supported | Supported | Supported |   -   |
| UBLOX_C030_U201      |     -     | Supported |     -     | Supported | Supported | Supported |   -   |
| UBLOX_EVA_NINA       |     -     | Supported |     -     | Supported | Supported | Supported |   -   |
| UBLOX_EVK_NINA_B1    |     -     | Supported |     -     | Supported | Supported | Supported |   -   |
| UBLOX_EVK_ODIN_W2    |     -     | Supported | Supported | Supported | Supported | Supported |   -   |
| UBRIDGE              | Supported | Supported |     -     | Supported | Supported | Supported |   -   |
| UHURU_RAVEN          |     -     | Supported | Supported | Supported | Supported | Supported |   -   |
| UNO_91H              | Supported | Supported |     -     | Supported | Supported | Supported |   -   |
| USENSE               | Supported | Supported |     -     | Supported | Supported | Supported |   -   |
| VBLUNO52             |     -     | Supported |     -     | Supported | Supported | Supported |   -   |
| VK_RZ_A1H            | Supported | Supported |     -     | Supported | Supported | Supported |   -   |
| WIO_3G               | Supported | Supported | Supported | Supported | Supported | Supported |   -   |
| WIO_BG96             | Supported | Supported | Supported | Supported | Supported | Supported |   -   |
| WIZWIKI_W7500        | Supported | Supported | Supported | Supported | Supported | Supported |   -   |
| WIZWIKI_W7500ECO     | Supported | Supported | Supported | Supported | Supported | Supported |   -   |
| WIZWIKI_W7500P       | Supported | Supported | Supported | Supported | Supported | Supported |   -   |
| XDOT_L151CC          |     -     | Supported |     -     | Supported | Supported | Supported |   -   |
Supported targets: 187`

This is the output for mbedls

`WARNING:mbedls.lstools_base:daplink entry: "1902" not found in platform database
| platform_name | platform_name_unique | mount_point | serial_port | target_id                                        | daplink_version |
|---------------|----------------------|-------------|-------------|--------------------------------------------------|-----------------|
| unknown       | None[0]              | D:          | COM31       | 19021301b015090e03b0150900000000000000002e127069 | 0254            |`

![mbedscreenshot](https://user-images.githubusercontent.com/46098510/62625703-c26d0880-b8f3-11e9-92f7-88f64b76044e.PNG)

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCELL-2124

**Comment by AriParkkila** [comment]
@vladdnikolic This sounds like an [mbed-cli](https://github.com/ARMmbed/mbed-cli) issue, please open a new issue there if problem still exits.
