### ISSUE TITLE
Example not running on custom Quectel port

### ISSUE THREAD

**Issue by iliapenev** [ARMmbed/mbed-os-example-cellular#164]
I'm doing custom Quectel MC60 port. It's based on MC26 target in mbed 5.14.
Modem is connected to STM Nucleo L476RG
Example could not be started. It could not get context. 

Problem appears to be here.
https://github.com/ARMmbed/mbed-os/blob/master/features/cellular/framework/AT/AT_CellularContext.cpp#L490

I tried with lwip.ppp enabled and disabled
```
            "lwip.ipv4-enabled": true,
            "lwip.ipv6-enabled": false,
            "lwip.ethernet-enabled": false,
            "lwip.ppp-enabled": false,
            "lwip.tcp-enabled": true,
            "QUECTEL_MC60.provide-default": true
```
[AT-Detailed-log.txt](https://github.com/ARMmbed/mbed-os-example-cellular/files/3709402/AT-Detailed-log.txt)

Using 
mbed-cli 1.10.1
gcc-arm-none-eabi-8-2018-q4-major

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCELL-2244

**Comment by iliapenev** [comment]
https://github.com/ARMmbed/mbed-os/pull/11717 Solves problem. 

Carefully checked all `_at.lock` `_at.unlock` pairs and I found where is problem.
