### ISSUE TITLE
mbed-os.lib doesn't use release version

### ISSUE THREAD

**Issue by toyowata** [ARMmbed/mbed-os-example-cellular#178]
The mbed-os.lib links to a master branch hash, not release version.

See here:
https://github.com/ARMmbed/mbed-os-example-cellular/issues/113

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCELL-2452

**Comment by paul-szczepanek-arm** [comment]
Master now points to release and development points to tip of master..
