### ISSUE TITLE
Support for Sim7000E

### ISSUE THREAD

**Issue by hasikp1** [ARMmbed/mbed-os-example-cellular#192]
Does the mbed os cellular support simcom modems? At the moment I am trying with a SIMCOM SIM7000E modem and Stm32 blue pill (stm32f103c8t6). It only contains 64Kbytes flash. I am receiving following errors.

[error log](https://pastebin.com/Q7t5UkZT)

How to reduce the memory usage.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCELL-2468

**Comment by kivaisan** [comment]
@hasikp1 We don't currently have support for SIMCOM modems.
64kB is very small, so full rtos probably won't fit. You may try baremetal profile if it fits for your purposes.
