### ISSUE TITLE
Export project to Keil - device not present

### ISSUE THREAD

**Issue by gggekov** [ARMmbed/mbed-os-example-cellular#41]
I export the blinky to Keil via
`$ mbed export -i uvision -m UBLOX_C030_U201`

When opening the project in Keil I get to an error message "Missing device Family Pack STM32F4xx_DFS:2.11.0"
![keil-missing-device-information](https://user-images.githubusercontent.com/31919465/33671490-ad327056-da9f-11e7-843a-1cafd1059837.png)

After clicking Import I am stuck at another error - "One or more Device Family Pack Devices are not present - would you like to choose another device"
![keil-choose-another-device](https://user-images.githubusercontent.com/31919465/33671331-3f9dcbda-da9f-11e7-9582-1d023b6875f1.png)

What is the workaround to this problem? Is there some configuration in Keil that could solve the issue? 

Kind regards,
George

**Comment by MarceloSalazar** [comment]
@theotherjimmy  please have a look

**Comment by theotherjimmy** [comment]
Looks very similar to 
https://github.com/ARMmbed/mbed-os/issues/5467

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCELL-277

**Comment by gggekov** [comment]
I've tried the fix from ARMmbed/mbed-os#5467 but I get compile error messages after following the described steps.  Is there something else I could try to properly import the C030 as a target in Keil?

**Comment by theotherjimmy** [comment]
@gggekov What compiler errors did you get?

**Comment by gggekov** [comment]
Hi @theotherjimmy 

Here are the error messages


```
irq_cm4f.S: Error:  #5: cannot open source input file "__UVISION_VERSION SETA 524": No such file or directory
irq_cm4f.S: __UVISION_VERSION SETA 524: 0 warnings, 1 error
irq_cm4f.S: Error: A1067E: Output file specified as 'mbed-os\rtos\TARGET_CORTEX\rtx5\RTX\Source\TOOLCHAIN_ARM\TARGET_RTOS_M4_M7\irq_cm4f.S', but it has already been specified as '.\build\irq_cm4f.o'
irq_cm4f.S: error: A1905U: Pre-processor step failed for '__UVISION_VERSION SETA 524'

startup_stm32f437xx.S: Error:  #5: cannot open source input file "__UVISION_VERSION SETA 524": No such file or directory
startup_stm32f437xx.S: __UVISION_VERSION SETA 524: 0 warnings, 1 error
startup_stm32f437xx.S: Error: A1067E: Output file specified as 'mbed-os\targets\TARGET_STM\TARGET_STM32F4\TARGET_STM32F437xG\device\TOOLCHAIN_ARM_STD\startup_stm32f437xx.S', but it has already been specified as '.\build\startup_stm32f437xx.o'
startup_stm32f437xx.S: error: A1905U: Pre-processor step failed for '__UVISION_VERSION SETA 524'
```

**Comment by theotherjimmy** [comment]
@gggekov That's caused by not having the device support pack installed correctly. Have you installed it?

**Comment by gggekov** [comment]
I've clicked the "install" button as per the first screenshot in the issue. However, after installing the missing packages I get stuck at the second screenshot from the description. 
Should I install all packages by hand?

**Comment by theotherjimmy** [comment]
I think it may need a `variant`, which requires a large update to cmsis-pack-manager.

**Comment by MarceloSalazar** [comment]
@adbridge I think we need to add this to the known-issue list

**Comment by adbridge** [comment]
@theotherjimmy is there an outstanding issue to update the cmsis-pack-manager ? If not , can we have one please , then we can add something to the known issues if required, referencing that issue.

**Comment by theotherjimmy** [comment]
@adbridge I created https://github.com/ARMmbed/cmsis-pack-manager/issues/16 to track the `variant` problem in cmsis-pack-manager.

**Comment by adbridge** [comment]
@theotherjimmy thanks

**Comment by ralphrmartin** [comment]
Any timescale on a fix for this? I also am stymied trying to export a project to uvision.

**Comment by ralphrmartin** [comment]
Soory, could you give me some direct instructions on what to do, please? The oblique references above are rather mystifying...

**Comment by theotherjimmy** [comment]
@ralphrmartin The text above claim that uvision complains with:

>"One or more Device Family Pack Devices are not present - would you like to choose another device"

You could choose the correct device at this point. I think that would at least allow you to build your code on devices with the "variant" problem.

**Comment by ralphrmartin** [comment]
I already tried that, and I am afraid that doe not give me a solution which builds. I still get the errors shown.

**Comment by theotherjimmy** [comment]
@ralphrmartin You could try replacing the string "STM32F437VG" with "STM32F437VGTx" in the to of your-project.uvprojx file. 
for example:
```xml 
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<Project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="project_projx.xsd">

  <SchemaVersion>2.1</SchemaVersion>

  <Header>### uVision Project, (C) Keil Software</Header>

  <Targets>
    <Target>
      <TargetName>fat-fs</TargetName>
      <ToolsetNumber>0x4</ToolsetNumber>
      <ToolsetName>ARM-ADS</ToolsetName>
      <TargetOption>
        <TargetCommonOption>
          <Device>STM32F437VG</Device>
          <Vendor>STMicroelectronics</Vendor>
          <PackID>Keil.STM32F4xx_DFP.2.11.0</PackID>
          <PackURL>http://www.keil.com/pack</PackURL>
```
would become 
```xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<Project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="project_projx.xsd">

  <SchemaVersion>2.1</SchemaVersion>

  <Header>### uVision Project, (C) Keil Software</Header>

  <Targets>
    <Target>
      <TargetName>fat-fs</TargetName>
      <ToolsetNumber>0x4</ToolsetNumber>
      <ToolsetName>ARM-ADS</ToolsetName>
      <TargetOption>
        <TargetCommonOption>
          <Device>STM32F437VGTx</Device>
          <Vendor>STMicroelectronics</Vendor>
          <PackID>Keil.STM32F4xx_DFP.2.11.0</PackID>
          <PackURL>http://www.keil.com/pack</PackURL>
```

**Comment by theotherjimmy** [comment]
In case it was not clear: "STM32F437VGTx" is the only variant of the UBLOX_C030_U201

**Comment by ralphrmartin** [comment]
Thanks, but in my case the device is a STM32F091RC. What replacement do I need in that case?

**Comment by ralphrmartin** [comment]
Aha, OK, I had to change it to STM32F091RCTx. Thanks for the pointer which got me going.

**Comment by theotherjimmy** [comment]
It's great to hear that you found the workaround you needed. I'm working on the verification of the variant parsing in cmsis-pack-manager. I'll try to keep you posted on my progress.

**Comment by kimlep01** [comment]
I had the same error when exporting the example with MTS_DRAGONFLY_F411RE: "Device not found STM32F411RE". This would happen even after installing the required "Keil.STM32F4xx_DFP.2.12.0" pack.

The workaround: 
select STM32F411RETx as the device
use ST-Link debugger
Debug: connect with pre-reset
Instructions found here: https://github.com/ARMmbed/mbed-os/issues/5467

**Comment by AnttiKauppila** [comment]
@theotherjimmy Any progress on this?

**Comment by theotherjimmy** [comment]
Yep, but nothing releasable yet. I have variant parsing in cmsis-pack-manager working. I need to add a few more bits and then integrate it with mbed-os.

**Comment by AriParkkila** [comment]
@theotherjimmy package update seems to work now with uVision V5.25.2.0 and Keil.STM32F4xx_DFP.2.13.0.

There is still a Warning #440: Requested device 'STM32F437VG' is subsituted with variant 'STM32F437VGTx' for target 'mbed-os-example-cellular'

I don't have actual HW to test if it really-really works :)

**Comment by theotherjimmy** [comment]
@AriParkkila The difference between the Variants of that device are restricted to package differences. That should work.

**Comment by AriParkkila** [comment]
@gggekov can you check if this issue is still valid?

**Comment by gggekov** [comment]
I no longer have this problem, I export a project and am able to open it in Keil normally(without the error message in the first post). Therefore I close the issue.
