### ISSUE TITLE
APN and Auth Info not available for MTB Dragonfly

### ISSUE THREAD

**Issue by dhwalters423** [ARMmbed/mbed-os-example-cellular#59]
APN and auth info for the MTB Dragonfly is not available:

In the documentation
In the example
On the board page: https://os.mbed.com/modules/multitech-dragonfly/

This is a blocker, without this information the module is not usable with cellular.

**Comment by AnttiKauppila** [comment]
ARM internal ref: IOTCELL-706

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCELL-707

**Comment by jarvte** [comment]
Hi,

APN and credentials are not Dragonfly specific but SIM card. 
APN is access point name specified by the operator which's SIM is in use.

https://os.mbed.com/teams/mbed-os-examples/code/mbed-os-example-cellular/

In mbed_app.json file you need to change "sim-pin-code" to match you sim card pin code.
"apn" can be left empty if you don't know the right apn.

Most probably you don't need to change "username" and "password".

**Comment by dhwalters423** [comment]
The Dragonfly MTB has an embedded SIM so I am thinking there must be a standard Apn. Would this come from the factory?

________________________________________

**Comment by jarvte** [comment]
Talked with @dhwalters423 and there is no esim and this case can be closed.
