### ISSUE TITLE
Out of memory on Mbed OS 5.8 with IAR compiler

### ISSUE THREAD

**Issue by AriParkkila** [ARMmbed/mbed-os-example-cellular#67]
IAR build takes too much memory on mbed-os-5.8.x. Although the example builds fine it fails at runtime with a trace message: _Operator new[] out of memory_

Mbed OS master has fixes to reduce memory consumption and that is working fine.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCELL-997

**Comment by jarvte** [comment]
will be fixed to 5.8.6
