### ISSUE TITLE
Example fails to compile for C030 in beta online comiler

### ISSUE THREAD

**Issue by dhwalters423** [ARMmbed/mbed-os-example-cellular#72]
When importing to the Beta online compiler: https://os-partnerbeta.mbed.com/compiler/ the example fails to compile with the following error:

![onlinecompilererror](https://user-images.githubusercontent.com/20944655/40777860-f8f35aee-64c6-11e8-948d-97a5f6c6161a.png)

On the live compiler: https://os.mbed.com/compiler/ the example compiles correctly and I am able to successfully run the example on the board.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCELL-1034

**Comment by gggekov** [comment]
I also encounter the same problem in https://os-partnerbeta.mbed.com.

**Comment by dhwalters423** [comment]
I have tried again later (today 07 June) and was able to successfully compile. @theotherjimmy is there any action we can take to increase bandwidth with the beta compiler?

**Comment by ashok-rao** [comment]
Thanks for re-checking this @dhwalters423 . Partner beta will undergo some maintenance after 5.9 OoB..such issues should be resolved after that. Issue can be closed now!
