### ISSUE TITLE
Test server echo.mbedcloudtesting.com issue

### ISSUE THREAD

**Issue by dhwalters423** [ARMmbed/mbed-os-example-cellular#78]
Test server echo.mbedcloudtesting.com responds to UDP only 50% of the time. It responds to TCP 100% of time time, and UDP exactly 50% of the time. 

Pointing to a different server, for example ciot.it-sgn.u-blox.com:5050, it is not reproducible, therefore I believe the issue is on the echo server itself.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCELL-1044

**Comment by dhwalters423** [comment]
This appears fixed, unable to reproduce as of 07/06/2018 REF: IOTCELL-1000
